import type { Metadata } from "next";
import Link from "next/link";
import Image from "next/image";
import { HeroSection } from "@/components/landing/HeroSection";
import { FeatureGrid } from "@/components/landing/FeatureGrid";
import { Testimonials } from "@/components/landing/Testimonials";
import { PricingSection } from "@/components/landing/PricingSection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  other: [
    {
      name: "talentapp:project_verification",
      content:
        "44dad16503de4ec34a02690a4eff3b17cda597b190e68125f0aa51cc4505b4c0a6dbfce2c04bd8d6524b5e6d92c8c206dc8739c088dac483ba7a45a4671491fb",
    },
  ],
};

export default function Home() {
  return (
    <main className="min-h-screen bg-gradient-to-br from-slate-950 via-black to-slate-900 text-slate-100">
      <header className="border-b border-white/5 py-6">
        <div className="mx-auto max-w-7xl px-6 sm:px-10 lg:px-16">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-4">
              <div className="rounded-3xl bg-slate-900/80 p-2 shadow-lg shadow-slate-950/20">
                <Image
                  src="/Taskflow_logo.png"
                  alt="TaskFlow"
                  width={64}
                  height={64}
                  className="rounded-3xl object-contain"
                  priority
                />
              </div>
              <span className="text-xl font-semibold tracking-tight text-white">TaskFlow</span>
            </div>
            <nav className="hidden gap-6 md:flex">
              <Link href="/product" className="text-sm text-slate-300 hover:text-white">Product</Link>
              <Link href="/pricing" className="text-sm text-slate-300 hover:text-white">Pricing</Link>
              <Link href="/docs" className="text-sm text-slate-300 hover:text-white">Docs</Link>
            </nav>
          </div>
        </div>
      </header>

      <HeroSection />
      <FeatureGrid />
      <Testimonials />
      <PricingSection />
    </main>
  );
}
